---
title: "read_data_from_web"
author: "Fang Wang"
date: "2024-10-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
setwd("/Users/fangwang/Downloads/P8105 Data Science I/Lecture 12/data_wrangling_ii")
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load the necessary libraries. 

```{r}
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url) # from "rvest"

drug_use_html
```

get the pieces I actually need:
```{r}
marj_use_df =
drug_use_html |>
  html_table() |> #in rvest 
  first() |>  # the first table will be select (?first to check which one we want to use)
  slice(-1) |> 
  as_tibble() # useless due to it was already a df
```

```{r}
url ="https://www.bestplaces.net/cost_of_living/city/new_york/new_york"

ny_cost_df = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |> 
html_table(header = TRUE) # we use this "header = TRUE" to use header

ny_cost_df
```

How to get data which is not in tables? (css selector)
How to add "selectorgadget" to bookmarker?
```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"
swm_html = read_html(swm_url)

title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec) 
```

Learning Assessment:
```{r}
books_url = "http://books.toscrape.com"

books_html = read_html(books_url)

books_titles = 
  books_html |>
  html_elements("h3") |>
  html_text2()

books_stars = 
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")

books_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text()

books = tibble(
  title = books_titles,
  stars = books_stars,
  price = books_price
)

```

